### ISSUE TITLE
Python ssl error?

### ISSUE THREAD

**Issue by Mistobaan** [wercker/cronetes#11]
Started to see this error on GKE

```
Traceback (most recent call last):
  File "/usr/bin/curator", line 7, in <module>
    import urllib3.contrib.pyopenssl
  File "/usr/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: Error loading shared library libssl.so.1.0.0: No such file or directory (needed by /usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so)
```
How to generate a Dockerfile from the wercker so I can manually patch it ?

**Comment by hatchan** [comment]
Currently we use these steps to deploy cronetes. You should be able to convert them to a Dockerfile equivalent. https://github.com/wercker/cronetes/blob/master/wercker.yml#L31-L52

I'll try to deploy a new docker image later today, which will probably solve this issue as well.
